export const RETRIEVE_OVERVIEW_CONTENT_SUCCESS = 'RETRIEVE_OVERVIEW_CONTENT_SUCCESS'
export const RETRIEVE_VISITORS_CONTENT_SUCCESS = 'RETRIEVE_VISITORS_CONTENT_SUCCESS'
export const RETRIEVE_EVENTS_CONTENT_SUCCESS = 'RETRIEVE_EVENTS_CONTENT_SUCCESS'

// Navigation 
export const UPDATE_NAV_TITLE = 'UPDATE_NAV_TITLE'

// Tab Controller
export const UPDATE_ACTIVE_TAB = 'UPDATE_ACTIVE_TAB'